ubuntu@yjh-master:~/homework$ ls
details-service.yaml  details.yaml  frontpage-service.yaml  frontpage.yaml  ingress-class.yaml  ingress.yaml
ubuntu@yjh-master:~/homework$ vi frontpage.yaml 
ubuntu@yjh-master:~/homework$ vi frontpage.yaml 
ubuntu@yjh-master:~/homework$ vi frontpage-service.yaml 
ubuntu@yjh-master:~/homework$ vi frontpage-service.yaml 
ubuntu@yjh-master:~/homework$ clear




















































ubuntu@yjh-master:~/homework$ ls
details-service.yaml  details.yaml  frontpage-service.yaml  frontpage.yaml  ingress-class.yaml  ingress.yaml
ubuntu@yjh-master:~/homework$ vi ingress.yaml 
ubuntu@yjh-master:~/homework$ vi ingress-class.yaml 























































apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  labels:
    app.kubernetes.io/component: controller
  name: app-ingress
  annotations:
    ingressclass.kubernetes.io/is-default-class: "true"
spec:
  controller: k8s.io/ingress-nginx
