apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /details
        pathType: Prefix
        backend:
          service:
            name: details-svc
            port:
              number: 80
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontpage-svc
            port:
              number: 80
